### ISSUE TITLE
Help me build this website in Reactjs!

### ISSUE THREAD

**Issue by Rhydium** [Rhydium/vurtuality-website#1]
Hello,

Vurtuality will be a community for developers to help each other and follow tutorials and make awesome projects together!

How you can help me is by making this a Reactjs project and make an example homepage.
Just fork the project, add your code and make a pull request. Thanks!

**Comment by ankitskvmdam** [comment]
I like to help you.

**Comment by Rhydium** [comment]
> I like to help you.

@ankitskvmdam, that would be very nice! Fork the repo, add the things you want to help with and make a pull request! :)

**Comment by ankitskvmdam** [comment]
@Rhydium can you please tell me that what are you expecting.

**Comment by Rhydium** [comment]
> @Rhydium can you please tell me that what are you expecting.

Most important for now is to have Reactjs set up and have a homepage.
When that's done, authentication needs to be made.
@ankitskvmdam
